main: dev.xaiter.spigot.dreambrickspawncommand.App
name: DreamBrickSpawnCommand
version: 0.1
api-version: 1.13
commands:
  spawn:
    description: Sends you back to spawn.  Must be asleep.  Must have at least 5 flint in the dream bank.
    usage: /spawn
    permission: dreambrickspawncommand.spawn
  balance:
    description: Tells you the amount of Flint you have in your dream bank account.
    usage: /balance
    permission: dreambrickspawncommand.balance
  bal:
    description: Tells you the amount of Flint you have in your dream bank account.
    usage: /bal
    permission: dreambrickspawncommand.balance
  rules:
    description: Tells you about the server's rules.
    usage: /rules
    permission: dreambrickspawncommand.rules
  discord:
    description: Gives a link to the server's discord
    usage: /discord
    permission: dreambrickspawncommand.discord
  clearchat:
    description: Clears the chat.  For staff use only.
    usage: /clearchat
    permission: dreambrickspawncommand.clearchat
  getbedloc:
    description: Gets a player's bed location.  For staff use only.
    usage: /getbedloc [name]
    permission: dreambrickspawncommand.getbedloc


permissions:
  dreambrickspawncommand.*:
    children:
      dreambrickspawncommand.spawn: true
      dreambrickspawncommand.balance: true
      dreambrickspawncommand.rules: true
      dreambrickspawncommand.discord: true
      dreambrickspawncommand.clearchat: true
      dreambrickspawncommand.getbedloc: true
  dreambrickspawncommand.spawn:
    description: Allows a player to return to spawn while in a bed.
    default: true
  dreambrickspawncommand.balance:
    description: Shows a player's dream flint balance.
    default: true
  dreambrickspawncommand.rules:
    description: Shows the rules, dang it.
    default: true
  dreambrickspawncommand.discord:
    description: Shows the server's discord.
    default: true
  dreambrickspawncommand.clearchat:
    description: Clears the chat.  For staff use only.
    default: false
  dreambrickspawncommand.getbedloc:
    description: Gets a player's bed location.  For staff use only.
    default: false    